---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
  python: ./requirements.txt
  system: ./bindep.txt

additional_build_steps:
  prepend: |
    RUN microdnf install --enablerepo=rhocp-4.11-for-rhel-8-x86_64-rpms --releasever=8.7 openshift-clients
    
  append: |
