---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: ghcr.io/ansible/community-ansible-dev-tools:latest
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
  python: ./requirements.txt
  system: ./bindep.txt
